# Generated by Django 3.2.1 on 2021-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='bowler_of_the_match',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='matches',
            name='looser_team',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='matches',
            name='man_of_the_match',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
