# Generated by Django 3.2.1 on 2021-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210731_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='bowler_of_the_match',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='matches',
            name='looser_team',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='matches',
            name='man_of_the_match',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner_team',
            field=models.CharField(max_length=32),
        ),
    ]
